// Arrays of randomness
const characters = [
    "Mermaid",
    "Fairy",
    "Wizard",
    "Warrior",
    "Vampire",
    "Dragon",
    "Goddess",
    "Cyborg",
    "Robot",
    "Angel",
    "Demon",
    "Alien",
    "Ghost",
    "Ninja",
    "Samurai",
    "Pirate",
    "Knight",
    "Bard",
    "Werewolf",
    "Zombie",
    "Giant",
    "Golem",
    "Sphinx",
    "Chimera",
    "Medusa",
    "Minotaur",
    "Harpy",
    "Kraken",
    "Cthulhu",
    "Gorgon",
    "Hydra",
    "Banshee",
    "Satyr",
    "Cyclops",
    "Dwarf",
    "Elf",
    "Centaur",
    "Manticore",
    "Frost Giant",
    "Sandworm",
    "Kelpie",
    "Thunderbird",
    "Leviathan",
    "Thundercats",
    "Gargantua",
    "Ogre",
    "Goblin",
    "Halfling",
    "Harlequin",
    "Jinn",
    "Kitsune",
    "Lich",
    "Mummy",
    "Naga",
    "Oni",
    "Pixie",
    "Siren",
    "Sylph",
    "Treant",
    "Unicorn",
    "Wendigo",
    "Wraith",
    "Xenomorph",
    "Yokai",
    "Zephyr",
    "Zombie Dragon",
    "Abomination",
    "Aasimar",
    "Arachne",
    "Cambion",
    "Cerberus",
    "Changeling",
    "Djinn",
    "Dryad",
    "Gargoyle",
    "Gnoll",
    "Grim Reaper",
    "Half-Demon",
    "Hobgoblin",
    "Ifrit",
    "Incubus",
    "Kappa",
    "Lizardfolk",
    "Mind Flayer",
    "Mongrelfolk",
    "Myconid",
    "Orc",
    "Sahuagin",
    "Shapeshifter",
    "Spectre",
    "Tengu",
    "Titan",
    "Witch",
    "Yeti",
    "Yuan-Ti",
    "Archer",
    "Barbarian",
    "Beastmaster",
    "Cleric",
    "Druid",
    "Enchanter",
    "Executioner",
    "Gladiator",
    "Gunslinger",
    "Healer",
    "Hunter",
    "Illusionist",
    "Infernal",
    "Inventor",
    "Jester",
    "Knight Errant",
    "Mage Hunter",
    "Marauder",
    "Necromancer",
    "Ninja Assassin",
    "Paladin",
    "Psionicist",
    "Ranger",
    "Rogue",
    "Runemaster",
    "Savage",
    "Scout",
    "Shaman",
    "Sniper",
    "Soldier",
    "Sorcerer",
    "Spellblade",
    "Spymaster",
    "Swashbuckler",
    "Templar",
    "Thief",
    "Time Traveler",
    "Tracker",
    "Trickster",
    "Vampire Hunter",
    "Warlock",
    "Warrior Monk",
    "Witch Doctor",
    "Wizard Hunter",
    "Zealot",
    "Arcanist",
    "Demon Hunter",
    "Dragon Slayer",
    "Elementalist",
    "Basilisk",
    "Cockatrice",
    "Cryptid",
    "Darkling",
    "Dracolich",
    "Elemental",
    "Enchantress",
    "Fenrir",
    "Gryphon",
    "Harpie",
    "Imp",
    "Jotun",
    "Lindworm",
    "Merfolk",
    "Nephilim",
    "Phoenix",
    "Roc",
    "Sasquatch",
    "Spriggan",
    "Troll",
    "Ursine",
    "Valkyrie",
    "Vargr",
    "Will-o'-the-wisp",
    "Wyvern",
    "Xorn",
    "Yeth Hound",
    "Zilant",
    "Ankheg",
    "Barghest",
    "Catoblepas",
    "Direwolf",
    "Empusa",
    "Frost Worm",
    "Giant Scorpion",
    "Homunculus",
    "Illithid",
    "Juggernaut",
    "Kobold",
    "Lamia",
    "Megafauna",
    "Nightmare",
    "Ophidian",
    "Peryton",
    "Quetzalcoatlus",
    "Rat King",
    "Salamander",
    "Alchemist",
    "Fire Elemental",
    "Water Elemental",
    "Earth Elemental",
    "Air Elemental",
    "Meteor Elemental",
    "Ice Elemental",
    "Light Elemental",
    "Shadow Elemental",
    "Astral Elemental",
    "Faun",
    "Moai",
    "Wight",
    "Bogeyman",
    "Revenant",
    "Selkie",
    "Pegasus",
    "Weretiger",
    "Werebear",
    "Seraphim",
    "Cherubim",
    "Hobbit",
    "Skinwalker",
    "Poltergeist",
    "Ghoul",
    "Fomorian",
    "Vodyanoi",
    "Kobaloi",
    "Graeae",
    "Erinyes",
    "Hippogriff",
    "Shade",
    "Kodama",
    "Strigoi",
    "Qilin",
    "Dullahan",
    "Headless Horseman",
    "Aswang",
    "Stymphalian Birds",
    "Tengu Warrior",
    "Koschei",
    "Nuckelavee",
    "Hellhound",
    "Simurgh",
    "Boogeyman",
    "Amphisbaena",
    "Amarok",
    "Tatzelwurm",
    "Kaiju",
    "Sea Serpent",
    "Raiju",
    "Wyrm",
    "Ooze",
    "Rakshasa",
    "Balrog",
    "Grotesque",
    "Warg",
    "Quasit",
    "Skull Knight",
    "Nephalem",
    "Archmage",
    "Astrophysicist",
    "Geomancer",
    "Lunar Deity",
    "Solar Deity",
    "Diviner",
    "Cartomancer",
    "Voodoo Priest",
    "Spiritualist",
    "Elemental Lord",
    "Shadowmancer",
    "Lunar Sorceress",
    "Wyrm Rider",
    "Geomancer",
    "Electromancer",
    "Quantum Mage",
    "Psychonaut",
    "Cosmonaut",
    "Seer",
    "Cosmic Serpent",
    "Galactic Entity",
    "Void Entity",
    "Astral Traveler",
    "Oracle",
    "Battle Mage",
    "Scholar",
    "High Priest",
    "Moon Priestess",
    "Sun Priest",
    "Seidr",
    "Feng Shui Master",
    "Metalbender",
    "Earthbender",
    "Firebender",
    "Waterbender",
    "Airbender",
    "Cosmic Bender",
    "Hexblade",
    "Shieldbearer",
    "Lorekeeper",
    "Peacekeeper",
    "Oathkeeper",
    "Master of Whispers",
    "Master of Arms",
    "Master of Beasts",
    "Master of Elements",
    "Death Knight",
    "Life Knight",
    "Chaos Knight",
    "Order Knight",
    "Cosmic Knight",
    "Temporal Knight",
    "Eldritch Knight",
    "Keyblade Master",
    "Astral Knight",
    "Lunar Knight",
    "Solar Knight",
    "Elemental Knight",
    "Undying",
    "Celestial",
    "Sea King",
    "Sky Queen",
    "Earth Mother",
    "Void Master",
    "Time Warden",
    "Cosmic Warden",
    "Lunar Warden",
    "Sun Warden",
    "Star Warden",
    "Shadow Warden",
    "Spirit Warden",
    "Ghost Pirate",
    "Sea Witch",
    "Lunar Witch",
    "Solar Witch",
    "Star Witch",
    "Wight King",
    "Oblivion Queen",
    "Astral Dragon",
    "Meteor Dragon",
    "Rainbow Dragon",
    "Stardust Dragon",
    "Lunar Phoenix",
    "Solar Phoenix",
    "Cosmic Phoenix",
    "Shadow Phoenix",
    "Flame Phoenix",
    "Ocean Phoenix",
    "Mystic Archer",
    "Time Archer",
    "Astral Archer",
    "Rocket Archer",
    "Void Archer",
    "Shadow Archer",
    "Spectral Archer",
    "Battle Seer",
    "Wind Dancer",
    "Shadow Dancer",
    "Star Dancer",
    "Spirit Dancer",
    "Oath Dancer",
    "Cosmic Dancer",
    "Chaos Dancer",
    "Order Dancer",
    "Sky Dancer",
    "Earth Dancer",
    "Flame Dancer",
    "Mystic Dancer",
    "Jungle Shaman",
    "Desert Shaman",
    "Mountain Shaman",
    "Island Shaman",
    "Sky Shaman",
    "Battle Shaman",
    "Shadow Shaman",
    "Star Shaman",
    "Chaos Shaman",
    "Order Shaman",
    "Master Chief",
    "Solid Snake",
    "Kratos",
    "Geralt of Rivia",
    "Cloud Strife",
    "Aloy",
    "Lara Croft",
    "Link",
    "Sonic",
    "Mario",
    "Zelda",
    "Samus Aran",
    "Sephiroth",
    "Arthur Morgan",
    "Niko Bellic",
    "Marcus Fenix",
    "Jill Valentine",
    "Sub-Zero",
    "Scorpion",
    "Goku",
    "Naruto",
    "Saitama",
    "Spike Spiegel",
    "Inuyasha",
    "Edward Elric",
    "Astolfo",
    "Alucard",
    "Light Yagami",
    "Asuka Langley",
    "Totoro",
    "Kenshin Himura",
    "Frodo Baggins",
    "Harry Potter",
    "Aragorn",
    "Gandalf",
    "Jon Snow",
    "Daenerys Targaryen",
    "Voldemort",
    "Lara Croft",
    "Samus Aran",
    "Aloy",
    "Jill Valentine",
    "Sailor Moon",
    "Homura Akemi",
    "Saber",
    "Mikasa Ackerman",
    "Asuka Langley Soryu",
    "Rem",
    "Nami",
    "Bulma",
    "Hermione Granger",
    "Galadriel",
    "Éowyn",
    "Daenerys Targaryen",
    "Arya Stark",
    "Leia Organa",
    "Ripley",
    "Wonder Woman",
  ];
  
  const objects = [
    "Sword",
    "Amulet",
    "Crystal",
    "Potion",
    "Book",
    "Staff",
    "Wand",
    "Ring",
    "Armor",
    "Helm",
    "Goblet",
    "Chalice",
    "Crown",
    "Scepter",
    "Medallion",
    "Orb",
    "Talisman",
    "Relic",
    "Binoculars",
    "Spear",
    "Dagger",
    "Bow and Arrow",
    "Shield",
    "Mace",
    "Hammer",
    "Axe",
    "Crossbow",
    "Whip",
    "Bolas",
    "Poison",
    "Chainsaw",
    "Katana",
    "Glaive",
    "Shuriken",
    "Sniper",
    "Gun",
    "T-shirt",
    "Shirt",
    "Skirt",
    "Sneakers",
    "Jeans",
    "Sunglasses",
    "Baseball Cap",
    "Boots",
    "High Heels",
    "Excalibur",
    "Mjölnir",
    "Lightsaber",
    "Cape",
    "Leather Jacket",
    "Dragonscale Armor",
    "Refined Armor",
    "Heavy Armor",
    "Light Armor",
    "Laptop",
    "Smartphone",
    "Tablet",
    "Camera",
    "Chains",
    "Rope",
    "Breastplate",
    "Gauntlets",
    "Shin Guards",
    "Cuirass",
    "Gorget",
    "Pauldrons",
    "Vambraces",
    "Greaves",
    "Beanie",
    "Bucket Hat",
    "Beret",
    "Cloak",
    "Sarong",
    "Kilt",
    "Chaps",
    "Quiver",
    "Holster",
    "Backpack",
    "Bracelet",
    "Choker",
    "Pendant",
    "Kimono",
    "Toga",
    "Fedora",
    "Tutu",
    "Turban",
    "Fanny Pack",
    "Combat Boots",
    "Aviator Glasses",
  ];
  
  const places = [
    "Underwater City",
    "Sky Castle",
    "Forest Temple",
    "Haunted Mansion",
    "Crystal Cavern",
    "Ice Fortress",
    "Volcano Lair",
    "Cyber City",
    "Steam Punk Metropolis",
    "Enchanted Garden",
    "Dark Dimension",
    "Celestial Palace",
    "Underground Tunnels",
    "Frozen Wasteland",
    "Desert Oasis",
    "Jungle Ruins",
    "Floating Island",
    "Time Warp",
    "Alien Planet",
    "Deep Space Station",
    "Magical Academy",
    "Futuristic Laboratory",
    "Ancient Library",
    "Artificial Intelligence Network",
    "Giant's Lair",
    "Chaos Realm",
    "Fairy Tale Castle",
    "Post-Apocalyptic City",
    "Interdimensional Nexus",
    "Dreamscape",
    "Abandoned Asylum",
    "Sunken Ship",
    "Forbidden Temple",
    "Lost City",
    "Parallel Universe",
    "Mystic Marsh",
    "Parallel World",
    "Underground Kingdom",
    "Dark Forest",
    "Crystal Palace",
    "Cursed Island",
    "Rainbow Valley",
    "Fire Mountain",
    "Hidden Cave",
    "Sky Kingdom",
    "Savage Wilds",
    "Mystical Mountain",
    "Ancient Pyramid",
    "Tropical Beach",
    "Elemental Plane",
    "Outer Space Colony",
    "Underground Bunker",
    "Lunar Base",
    "Forgotten Citadel",
    "Ancient Catacombs",
    "Holographic Theme Park",
    "Crystal Lake",
    "Floating Market",
    "Underground Volcano",
    "Abandoned Space Station",
    "Surreal Landscape",
    "Crystal Tower",
    "Mystical Island",
    "Mysterious Labyrinth",
    "Jungle Canopy",
    "Enchanted Marketplace",
    "Sunken Cityscape",
    "Haunted Forest",
    "Space Elevator",
    "Crystal Lagoon",
    "Magma Chamber",
    "Thundering Waterfall",
    "Ethereal Valley",
    "Abandoned Subway System",
    "Mirrored City",
    "Ancient Citadel",
    "Frozen Tundra",
    "Haunted Amusement Park",
    "Sunken Ruins",
    "Enchanted Castle",
    "Sandswept Canyon",
    "Orbital Station",
    "Lost Wilderness",
    "Aurora Borealis",
    "Giant Redwood Forest",
    "Futuristic Casino",
    "Mythical Underworld",
    "Infinite Desert",
    "Mystical Labyrinth",
    "Galactic Gateway",
    "Submerged Cavern",
    "Eternal Ice Fields",
    "Dark Matter Realm",
    "Holographic City",
    "Celestial Observatory",
    "Nebula Cluster",
    "Glacier National Park",
    "Undiscovered Island",
    "Underground Laboratory",
    "Retro Arcade",
    "Crystal Gardens",
    "Chromatic Coastline",
    "Iridescent Reef",
    "Lunar Colony",
    "Rainforest Canopy",
    "Hyperborean Forest",
    "Tesseract Station",
    "Magnetic Caves",
    "Abyssal Trench",
    "Interstellar Hub",
    "Exoplanet Outpost",
    "Emerald Canyon",
    "Spectral Sands",
    "Lost Oasis",
    "Nebula Nebula",
    "Astral Nexus",
    "Radiant Cityscape",
    "Euphoric Eden",
    "Pixelated Wonderland",
    "Clockwork Metropolis",
    "Ethereal Plane",
    "Neo-Tokyo Megapolis",
    "Doomsday New York",
    "Osaka",
    "Futuristic New York",
    "Gothic Paris",
    "Cybernetic London",
    "Spectral Rome",
    "Mythical Cairo",
    "Enchanted Sydney",
    "Steampunk San Francisco",
    "Eerie New Orleans",
    "Epic Berlin",
    "Venice of Dreams",
    "Steampunk London",
    "Retrofuturistic Moscow",
    "Ruins of Rome",
    "Shanghai Skybridge",
    "Cybernetic Arena",
    "Witch's Cottage",
    "Infinite Jungle",
    "Robot Zoo",
    "Elven Treehouse",
    "Desert Mirage",
    "Virtual Reality Playground",
    "Crystalized Cave",
    "Dragon's Den",
    "Sacred Waterfall",
    "Dimensional Library",
    "Moonlit Orchard",
    "Alchemist's Tower",
    "Haunted Graveyard",
    "Oceanic Abyss",
    "Temporal Café",
    "Lost Atlantis",
    "Vampire Castle",
    "Invisible Maze",
    "Cherry Blossom Temple",
    "Digital Utopia",
    "Celestial Zoo",
    "Pirate Cove",
    "Forest of Echoes",
    "Mars Colony",
    "Alien Zoo",
    "Petrified Forest",
    "Goblin Market",
    "Cursed Zoo",
    "Eldritch Library",
    "Heavenly Observatory",
    "Magic School",
    "Undying Desert",
    "Temporal Rift",
    "Robot Factory",
    "Spacecraft Graveyard",
    "Arctic Wilderness",
    "Lush Savannah",
    "Carnival of Nightmares",
    "Starlit Beach",
  ];
  
  const elements = [
    "Fire",
    "Water",
    "Air",
    "Earth",
    "Lightning",
    "Ice",
    "Nature",
    "Darkness",
    "Light",
    "Metal",
    "Shadow",
    "Blood",
    "Lava",
    "Crystal",
    "Poison",
    "Time",
    "Space",
    "Gravity",
    "Sound",
    "Electricity",
    "Plasma",
    "Radiation",
    "Magma",
    "Smoke",
    "Steam",
    "Void",
    "Wind",
    "Plantlife",
    "Moon",
    "Sun",
    "Stars",
    "Sand",
    "Ash",
    "Quicksand",
    "Frost",
    "Acid",
    "Thunder",
    "Psychic Energy",
    "Dimensional Rift",
    "Cosmic Dust",
    "Spirit",
    "Gravity Waves",
    "Invisibility",
    "Psychokinesis",
    "Luminosity",
    "Chaos",
    "Magnetism",
    "Antimatter",
    "Pulse",
    "Gravity Flux",
    "Echolocation",
    "Photosynthesis",
    "Radiance",
    "Oblivion",
    "Memory",
    "Gravity Well",
    "Nanobots",
    "Nuclear Energy",
    "Psionics",
    "Phase Shift",
  ];
  
  const adjectives = [
    "Ethereal",
    "Whimsical",
    "Mysterious",
    "Eerie",
    "Futuristic",
    "Gothic",
    "Serene",
    "Enigmatic",
    "Otherworldly",
    "Surreal",
    "Mythical",
    "Transcendent",
    "Celestial",
    "Nostalgic",
    "Hypnotic",
    "Cinematic",
    "Awe-Inspiring",
    "Epic",
    "Radiant",
    "Ornate",
    "Holographic",
    "Prismatic",
    "Intricate",
    "Majestic",
    "Harmonious",
    "Opulent",
    "Spectral",
    "Dramatic",
    "Glimmering",
    "Dreamlike",
    "Hyperrealistic",
    "Melancholic",
    "Psychedelic",
    "Retro-Futuristic",
    "Post-Apocalyptic",
    "Neon",
    "Saturated",
    "Sculptural",
    "Minimalist",
    "Abstract",
    "Vibrant",
    "Cosmic",
    "Organic",
    "Luminous",
    "Tranquil",
    "Whirlwind",
    "Hazy",
    "Fragile",
    "Crisp",
    "Dynamic",
    "Galactic",
    "Flamboyant",
    "Shimmering",
    "Misty",
    "Idyllic",
    "Nebulous",
    "Rustic",
    "Fleeting",
    "Nimble",
    "Spirited",
    "Geometric",
    "Polygonal",
    "Golden Hour",
    "Underwater",
    "Pokémon",
  ];
  
  const styles = [
    "Digital Art",
    "Surrealism",
    "Concept Art",
    "Illustration",
    "Character Design",
    "Anime",
    "Realism",
    "Impressionism",
    "Pop Art",
    "Steampunk",
    "Pixel Art",
    "Graffiti Art",
    "Fantasy Art",
    "Futurism",
    "Art Deco",
    "Minimalism",
    "Street Art",
    "Hyperrealism",
    "Glitch Art",
    "Photorealism",
    "Calligraphy",
    "Ink",
    "Woodcut Print",
    "Manga",
    "Sketch",
    "Drawing",
    "Doodle",
    "Dot Art",
    "Stipple",
    "Anatomical Drawing",
    "Visual Novel",
    "Graphic Novel",
    "Hand-Drawn",
    "Graphite",
    "Colored Pencil",
    "Pastel Art",
    "Blackboard",
    "Splatter Paint",
    "Paper-Marbling",
    "Logo",
    "Comic Book",
    "Poster",
    "Kirigami",
    "Origami",
    "Frame",
    "Wall Decal",
    "Banner",
    "Papercutting",
    "Ice Carving",
    "Linocut",
    "Wood-Carving",
    "Light Art",
    "Bokeh",
    "Wildlife Photography",
    "Portrait",
    "Microscopic",
    "Ultra-Wide Angle",
    "Depth of Field",
    "Closeup",
    "Blur Effect",
    "Lens Flare",
    "Punk",
  ];
  
  const colors = [
    "Warm Color Palette",
    "Colorful",
    "Rainbow",
    "Spectral Color",
    "Inverted Colors",
    "Neon",
    "Electric Colors",
    "Complimentary-Colors",
    "Dark Mode",
    "Triadic-Colors",
    "Polychromatic Colors",
    "Tones of Black",
    "Black and White",
    "Monochrome",
    "Sepia",
    "High Contrast",
    "Low Contrast",
    "Technicolor",
    "Atari Graphics",
    "Adobe RGB",
    "Hexadecimal",
    "Vintage",
    "Pastel Palette",
    "Metallic Colors",
    "Fire Tones",
    "Shades of Gray",
    "Pop Art Colors",
    "Night Colors",
    "Cool Tones",
    "Warm Tones",
    "Red Monochrome",
    "Green Monochrome",
    "Blue Monochrome",
    "Yellow Monochrome",
    "Purple Monochrome",
  ];
  
  const artists = [
    "Alan Lee",
    "Cyril Rolando",
    "David Mack",
    "Donato Giancola",
    "Greg Rutkowski",
    "Ismail Inceoglu",
    "John Berkey",
    "Michael Garmash",
    "Peter Mohrbacher",
    "Sparth",
    "Vincent Di Fate",
    "Akihiko Yoshida",
    "Artgerm",
    "Charlie Bowater",
    "Frank Frazetta",
    "Hsiao-Ron Cheng",
    "Ilya Kuvshinov",
    "Joshua Middleton",
    "Krenz Cushart",
    "Lois Van Baarle",
    "Makoto Shinkai",
    "Rossdraws",
    "Wenjun Lin",
    "Anna Dittmann",
    "Agnes Cecile",
    "Alphonse Mucha",
    "Audrey Kawasaki",
    "Boris Vallejo",
    "Carne Griffiths",
    "Conrad Roset",
    "JC Leyendecker",
    "Joseph Lorusso",
    "Jovana Rikalo",
    "Karol Bak",
    "Marco Mazzoni",
    "Miho Hirano",
    "Rebeca Saray",
    "Robert McGinnis",
    "Russ Mills",
    "Tom Bagshaw",
    "Tristan Eaton",
    "Ed Mell",
    "Jessica Rossier",
    "Hubert Robert",
    "Ian McQue",
    "Marc Simonetti",
    "Raphael Lacoste",
    "Bernie Wrightson",
    "H.R. Giger",
    "Richard Corben",
    "Wayne Barlowe",
    "Zdzislaw Beksinski",
    "Hokusai Katsushika",
    "Akira Toriyama",
    "Eiichiro Oda",
    "Masashi Kishimoto",
    "Osamu Tezuka",
    "Vincent van Gogh",
    "Leonardo da Vinci",
    "Frida Kahlo",
    "Pablo Picasso",
    "Georgia O'Keeffe",
    "Ansel Adams",
    "Dorothea Lange",
    "Robert Capa",
    "Cindy Sherman",
    "Henri Cartier-Bresson",
    "Michelangelo",
    "Auguste Rodin",
    "Louise Bourgeois",
    "Donatello",
    "Constantin Brâncuși",
    "Milton Glaser",
    "Paul Rand",
    "Jessica Walsh",
    "Shepard Fairey",
    "Mary Blair",
    "Charles Schulz",
    "Bill Watterson",
    "Jack Kirby",
    "Stan Lee",
    "R. Crumb",
    "Banksy",
    "JR",
    "Shepard Fairey",
    "Kobra",
    "Obey",
    "Rembrandt van Rijn",
    "Claude Monet",
    "Edvard Munch",
    "Caravaggio",
    "Johannes Vermeer",
    "Salvador Dalí",
    "John Singer Sargent",
    "Egon Schiele",
    "Marc Chagall",
    "Henri Matisse",
    "Edgar Degas",
    "Jackson Pollock",
    "Wassily Kandinsky",
    "Édouard Manet",
    "Diego Rivera",
    "Giotto di Bondone",
    "Amedeo Modigliani",
    "Toulouse-Lautrec",
    "Piet Mondrian",
    "Francisco Goya",
    "Hayao Miyazaki",
    "Genndy Tartakovsky",
    "Naoko Takeuchi",
    "Hiromu Arakawa",
    "Bruce Timm",
    "Makoto Shinkai",
    "Rebecca Sugar",
    "Alex Hirsch",
    "Pendleton Ward",
    "Bryan Konietzko and Michael Dante DiMartino",
    "Junji Ito",
    "Yoshitaka Amano",
    "Rumiko Takahashi",
    "Mamoru Hosoda",
    "Craig McCracken",
    "Glen Keane",
    "Tite Kubo",
    "Hirohiko Araki",
    "Nick Park",
    "Tetsuya Nomura",
    "Annie Leibovitz",
    "Steve McCurry",
    "Yousuf Karsh",
    "Diane Arbus",
    "Vivian Maier",
    "Richard Avedon",
    "Sebastião Salgado",
    "Irving Penn",
    "Robert Frank",
    "Gordon Parks",
    "Studio Ghibli",
    "Madhouse",
    "Pixar Animation Studios",
    "Toei Animation",
    "Rooster Teeth",
    "Ankama Studio",
    "Ankama Games",
  ];
  
  const prefixes = [
    "Zombie",
    "Superhero",
    "Robot",
    "Pirate",
    "Alien",
    "Wizard",
    "Vampire",
    "Werewolf",
    "Ninja",
    "Dragon",
    "Cyborg",
    "Time-traveler",
    "Space",
    "Giant",
    "Tiny",
    "Invisible",
    "Goblin",
    "Goddess",
    "Sorceress",
    "Witch",
    "Ghost",
    "Saiyan",
    "Astral",
    "Bionic",
    "Steampunk",
    "Chrono",
    "Quantum",
    "Cybernetic",
    "Galactic",
    "Arcane",
    "Mystic",
    "Eldritch",
    "Apocalyptic",
    "Elemental",
    "Divine",
    "Fallen",
    "Monstrous",
    "Mutated",
    "Psionic",
    "Supernatural",
    "Feral",
    "Aquatic",
    "Subterranean",
    "Celestial",
    "Phantasmal",
    "Revenant",
    "Living",
    "Sentient",
    "Spectral",
    "Mechanical",
    "Biological",
    "Mythic",
    "Fabled",
    "Demonic",
    "Shadow",
    "Lunar",
    "Solar",
    "Stellar",
    "Arctic",
    "Tropical",
    "Imperial",
    "Royal",
    "Majestic",
    "Temporal",
    "Dimensional",
    "Vigilante",
    "Cosmic",
    "Primordial",
    "Cursed",
    "Blessed",
    "Synthetic",
    "Aether",
    "Serpentine",
    "Nomadic",
    "Tribal",
    "High",
    "Low",
    "Cunning",
    "Ruthless",
    "Infernal",
    "Heavenly",
    "Abyssal",
    "Unholy",
    "Radiant",
    "Miraculous",
    "Noble",
    "Twisted",
    "Tormented",
    "Warped",
    "Grotesque",
    "Ascendant",
    "Dystopian",
    "Utopian",
    "Relentless",
    "Carnal",
    "Martial",
    "Aerial",
    "Aquamarine",
    "Ivory",
    "Amber",
    "Obsidian",
    "Coral",
    "Verdant",
    "Frigid",
    "Fiery",
    "Volcanic",
    "Magnetic",
    "Elastic",
    "Immortal",
    "Mortal",
    "Digital",
    "Equestrian",
    "Feathered",
    "Scaled",
    "Translucent",
    "Ornamental",
    "Alchemical",
    "Incorporeal",
    "Reclusive",
    "Avian",
    "Venomous",
    "Electric",
  ];
  
  const suffixes = [
    "dancing",
    "flying",
    "running",
    "singing",
    "fighting",
    "swimming",
    "climbing",
    "jumping",
    "laughing",
    "crying",
    "shouting",
    "exploring",
    "sleeping",
    "eating",
    "walking",
    "sneaking",
    "teleporting",
    "summoning",
    "twirling",
    "mystifying",
    "illuminating",
    "contemplating",
    "enchanting",
    "whispering",
    "wandering",
    "daydreaming",
    "captivating",
    "vanishing",
  ];
  
  const improvers = [
    "masterpiece, trending on artstation",
    "trending on deviantart",
    "award-winning",
    "masterpiece",
    "intricate and detailed",
    "hyper-realistic",
    "ethereal beauty",
    "surreal masterpiece",
    "jaw-dropping",
    "psychedelic",
    "colorful and vibrant",
  ];


// combine arrays together
var allArrays = [characters, objects, places, elements, adjectives, styles, colors, artists, prefixes, suffixes, improvers];

function generatePrompts() {
    // limit the number of prompt
    var promptCount = Math.floor(Math.random() * (50 - 20 + 1)) + 20;

    var prompt = "";

    for (var i = 0; i < promptCount; i++) {
        // choose an array randomly
        var arrayIndex = Math.floor(Math.random() * allArrays.length);
        var array = allArrays[arrayIndex];

        // choose an element from the array chosen
        var elementIndex = Math.floor(Math.random() * array.length);
        var element = array[elementIndex];

        // put the element to the prompt
        prompt += element + " ";
    }

    return prompt.trim();  // return the prompt
}
